#cloud-config
autoinstall:
  version: 1
  identity:
    # hostname: ${VM_HOSTNAME} # ホスト名はスクリプトで設定されるため、ここでは不要かもしれないが念のため
    username: CI_USERNAME
    password: CI_PASSWORD_HASH
  locale: ja_JP.UTF-8
  keyboard:
    layout: jp
    toggle: null
  network:
    version: 2
    ethernets:
      enp1s0: # ネットワークインターフェース名 (ProxmoxのVM設定によって異なる場合があります)
        # dhcp4: true
        # 固定IPアドレスの例:
        addresses:
          - VM_IP_ADDRESS
        gateway4: VM_GATEWAY
        nameservers:
          addresses: [VM_DNS_SERVERS]
  ssh:
    install-server: true
    password_authentication: true

runcmd:
  - apt update
  - apt upgrade -y
  - apt autoremove -y
  - systemctl restart ssh
  - echo "Cloud-init finished successfully." > /var/log/cloud-init-status.log
